#!/usr/bin/env bash
set -e

# install spikeinterface
# pip install -U --no-cache-dir spikeinterface[full]==0.97.1

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout 5369cb0e799a52a1ccb1de6feacf05c41f65dd95
pip  install --no-cache-dir .[full]
cd ..